api_platform:
    title: 'HYD API Plarform demo'
    description: 'API documentation - OpenAPI / Swagger'
    version: 'v1'
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Dto'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            Bearer:
                name: Authorization
                type: header
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    oauth:
        enabled: true
        type: 'oauth2'
        flow: 'password'
        tokenUrl: '/api/v1/oauth2/token'
        authorizationUrl: '/api/v1/oauth2/authorize'
        scopes: []